name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          filter: blob:none

      - name: Git Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v6.0.1
        with:
          major_pattern: 'major:'
          bump_each_commit: true
          version_from_branch: true

      - name: Docker Hub Login
        uses: docker/login-action@v3.7.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v6.19.2
        env:
          IMAGE: dieginin/scheduly-backend
          VERSION: ${{ steps.version.outputs.version }}
        with:
          push: true
          tags: ${{ env.IMAGE }}:${{ env.VERSION }},${{ env.IMAGE }}
          platforms: linux/amd64,linux/arm64
